CREATE DATABASE vet_clinic;
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL(5, 2)
);
ALTER TABLE animals ADD species VARCHAR(255);

--- Create table owners: 
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255),
    age INT NOT NULL,
    PRIMARY KEY (id)
);
----Create a table named species with the following columns:
---id: integer (set it as autoincremented PRIMARY KEY)
--name: string

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);
----Make sure that id is set as autoincremented PRIMARY KEY
ALTER TABLE animals
ADD PRIMARY KEY (id);
----
-- Remove column species:

ALTER TABLE animals
DROP species;

-- Add column species_id which is a foreign key referencing species table:

-- First, I add the 'species_id' column
ALTER TABLE animals
ADD species_id INT;

-- Then, I create the foreign key constraint
ALTER TABLE animals
ADD CONSTRAINT fk_species
FOREIGN KEY (species_id) REFERENCES species(id);

---Add column owner_id which is a foreign key referencing the owners table:
ALTER TABLE animals
ADD  owner_id INT;

-- Then, create the foreign key constraint
ALTER TABLE animals
ADD CONSTRAINT fk_owner
FOREIGN KEY (owner_id) REFERENCES owners(id);
---------
---Create a table named vets with the following columns: id, name, age, date_of_graduation:
CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    age INT,
    date_of_graduation DATE
);
-- Create the "specializations" join table
CREATE TABLE specializations (
  vet_id INT,
  species_id INT,
  FOREIGN KEY (vet_id) REFERENCES vets(id),
  FOREIGN KEY (species_id) REFERENCES species(id)
);

--- visits Join table
CREATE TABLE visits (
  vet_id INT,
  animals_id INT,
  visit_date DATE,
  FOREIGN KEY (vet_id) REFERENCES vets(id),
  FOREIGN KEY (animals_id) REFERENCES animals(id)
);
/*Add email column to owners table*/
-- ALTER TABLE owners ADD COLUMN email VARCHAR(120);

/*Drop Not Null constraints on owners table full_name & age column*/
ALTER TABLE owners ALTER COLUMN full_name DROP NOT NULL;
ALTER TABLE owners ALTER COLUMN age DROP NOT NULL;
--- 

--- let create the index: 
 CREATE INDEX idx_animal_id ON visits (animals_id);

 CREATE INDEX idx_visits_id ON visits (vet_id);

CREATE INDEX idx_owner_email ON owners (email);